<?php

namespace App\Observers\Moe;

use App\Models\Moe\ProjectCost;
use Drivezy\LaravelUtility\Library\Message;
use Drivezy\LaravelUtility\Observers\BaseObserver;
use Illuminate\Database\Eloquent\Model as Eloquent;

/**
 * Class ProjectCostObserver
 * @package App\Observers\Moe
 */
 class ProjectCostObserver extends BaseObserver {

    /**
     * @var array
     */
    protected $rules = [
    ];

    public function saving (Eloquent $model)
    {
        $record = ProjectCost::where('project_id', $model->project_id)->where('cost_head_id', $model->cost_head_id)->first();
        if($record && $record->id != $model->id){
            Message::warn('Duplicate project cost..');
            $model->setAttribute('errors', 'Duplicate project cost..');

            return false;
        }
        return parent::saving($model); // TODO: Change the autogenerated stub
    }
 }
