<?php

namespace App\Observers\Moe;

use App\Models\Moe\ProjectSchedule;
use App\Models\Moe\WorkActivity;
use Drivezy\LaravelUtility\Library\DateUtil;
use Drivezy\LaravelUtility\Library\Message;
use Drivezy\LaravelUtility\Observers\BaseObserver;
use Illuminate\Database\Eloquent\Model as Eloquent;

/**
 * Class ProjectScheduleObserver
 * @package App\Observers\Moe
 */
class ProjectScheduleObserver extends BaseObserver
{

    /**
     * @var array
     */
    protected $rules = [
    ];

    /**
     * @param Eloquent $model
     * @return bool|Eloquent
     */
    public function saving (Eloquent $model)
    {
        //check for duplicate record
        $record = ProjectSchedule::where('project_id', $model->project_id)->where('work_activity_id', $model->work_activity_id)->first();
        if ( $record && $record->id != $model->id ) {
            Message::warn('Duplicate project activity..');
            $model->setAttribute('errors', 'Duplicate project activity..');

            return false;
        }

        //always add name what is defined in work activity
        $model->name = WorkActivity::find($model->work_activity_id)->name;

        //calculate the duration based on the model data
        if ( $model->estimate_start_date && $model->estimate_end_date ) {
            $days = DateUtil::getDateDifference($model->estimate_start_date, $model->estimate_start_date);
            $model->estimated_duration = $days;
        }

        if ( $model->actual_start_date && $model->actual_end_date ) {
            $days = DateUtil::getDateDifference($model->actual_start_date, $model->actual_start_date);
            $model->actual_duration = $days;
        }

        return parent::saving($model); // TODO: Change the autogenerated stub
    }

}
