<?php

namespace App\Observers\Sys;

use Drivezy\LaravelUtility\Observers\BaseObserver;
use Illuminate\Database\Eloquent\Model as Eloquent;
use Illuminate\Support\Facades\Hash;

/**
 * Class OpenPropertyObserver
 * @package App\Observers\Sys
 */
class UserObserver extends BaseObserver
{

    /**
     * @var array
     */
    protected $rules = [
    ];

    /**
     * @param Eloquent $model
     * @return bool
     */
    public function saving (Eloquent $model)
    {
        if ( $model->password )
            $model->password = Hash::make($model->password);

        return parent::saving($model); // TODO: Change the autogenerated stub
    }
}
